version: 0.2

env:
  shell: bash
phases:
  install:
    runtime-versions:
      php: 8.2
    commands:
      - echo "install step"

  pre_build:
    commands:
      - echo "pre build"
  build:
    commands:
      - echo "composer install"
      - echo "drush commands"
      - ls -lah
      - cd ..
      - ls -lah
  post_build:
    commands:
      - echo "Zip the report"
    finally:
      - echo "Remove all containers"
