version: 0.2

env:
  shell: bash
  git-credential-helper: yes
  parameter-store:
    ssh_key: "/CodeBuild/DRPL-ECOM-DEV-Deploy-prod/ACQUIA_SSH"
    AC_API_KEY: "/CodeBuild/DRPL-ECOM-DEV-Deploy-prod/AC_API_KEY"
    AC_API_SECRET: "/CodeBuild/DRPL-ECOM-DEV-Deploy-prod/AC_API_SECRET"
    deployType: "/CodeBuild/DRPL-ECOM-DEV-Deploy-prod/deployType"
    branchName: "/CodeBuild/DRPL-ECOM-DEV-Deploy-prod/branchName"
  variables:
    buildBranch: "feature/BIT-2874-cpe-redesign-build"
phases:
  pre_build:
    commands:
      # Authenticate SSH keys
      - mkdir -p ~/.ssh
      - echo "$ssh_key" > ~/.ssh/id_rsa
      - chmod 400 ~/.ssh/id_rsa
      - ls ~/.ssh
      - eval "$(ssh-agent -s)"
      - ssh-keyscan svn-37631.prod.hosting.acquia.com >>~/.ssh/known_hosts
      - ssh-keyscan staging-36686.prod.hosting.acquia.com >>~/.ssh/known_hosts
      # clone Artifact Repo
      - git clone atgeacebecker@svn-37631.prod.hosting.acquia.com:atgeacebecker.git --branch="$buildBranch"
      - ls -lah
      - cd atgeacebecker
  build:
    commands:
      - echo $(date)
      - echo $deployType
      - echo $buildBranch
      - echo $branchName
      - |
        if [ "$deployType" = "Full" ]; then
          # bash scripts/cpe-redesign/deploy-cpe-redesign-all.sh $branchName
          echo "deploy full"
        elif [ "$deployType" = "CodeOnly" ]; then
          # bash scripts/cpe-redesign/deploy-cpe-redesign-partial-code-and-config.sh $branchName
          echo "deploy code only"
        else
        	echo "ERROR: Could not determine deployType!"
        	exit 1;
        fi
  post_build:
    commands:
      - echo $(date)
      - cd ..
      - rm -rf atgeacebecker