#!/bin/sh


JIRA_TICKET=$(echo "$TRAVIS_PULL_REQUEST_BRANCH" | grep -o '[A-Z]\+-[0-9]\+' )
echo "${JIRA_TICKET}"

TICKET_STATUS=$( curl -u $JIRA_USER_NAME:$JIRA_API_TOKEN -X GET -H "Content-Type: application/json" "https://beckeredu.atlassian.net/rest/api/3/issue/${JIRA_TICKET}" | jq '.fields.status.id' | grep -o '[0-9]\+')
echo "Jira Status need to be Code Review -- 10050"
echo "Current status: ${TICKET_STATUS}"

# The Code Review status ID is 10050
if [ "$TICKET_STATUS" = "10050" ]; then
    echo "Jira Status Correct!";
else
    curl --request PUT \
  --url "https://beckeredu.atlassian.net/rest/api/3/issue/${JIRA_TICKET}" \
  --user $JIRA_USER_NAME:$JIRA_API_TOKEN \
  --header 'Accept: application/json' \
  --header 'Content-Type: application/json' \
  --data '{
        "update": {
            "labels": [
                {
                    "add": "pr-process-issue"
                }
            ]
        }
    }' |
    jq '.'

    # curl --request PUT \
    # --url 'https://your-domain.atlassian.net/rest/api/2/app/field/{fieldIdOrKey}/value' \
    # --user 'email@example.com:<api_token>' \
    # --header 'Accept: application/json' \
    # --header 'Content-Type: application/json' \
    # --data '{
    # "updates": [
    #         {
    #             "issueIds": [
    #                 10010
    #             ],
    #             "value": "new value"
    #         }
    #     ]
    # }'

   curl --request POST \
  --url "https://beckeredu.atlassian.net/rest/api/3/issue/${JIRA_TICKET}/comment" \
  --user $JIRA_USER_NAME:$JIRA_API_TOKEN \
  --header 'Accept: application/json' \
  --header 'Content-Type: application/json' \
  --data '{
        "body": {
            "content": [
            {
                "content": [
                {
                    "text": "Jira Automation Message: Pull Request opens with wrong status. Please change the Ticket to Code Review to log work hours.",
                    "type": "text"
                }
                ],
                "type": "paragraph"
            }
            ],
            "type": "doc",
            "version": 1
        }
    }' |
    jq '.'
fi
