#!/bin/sh


JIRA_TICKET=$(echo "$TRAVIS_PULL_REQUEST_BRANCH" | grep -o '[A-Z]\+-[0-9]\+' )
echo "${JIRA_TICKET}"

TICKET_STATUS=$( curl -u $JIRA_USER_NAME:$JIRA_API_TOKEN -X GET -H "Content-Type: application/json" "https://beckeredu.atlassian.net/rest/api/3/issue/${JIRA_TICKET}" | jq '.fields.status.id' | grep -o '[0-9]\+')
echo "Jira Status need to be Code Review -- 10050"
echo "Current status: ${TICKET_STATUS}"

# The Code Review status ID is 10050
if [ "$TICKET_STATUS" = "10050" ]; then
    echo "Jira Status Correct!";
else
    curl -u $JIRA_USER_NAME:$JIRA_API_TOKEN -X POST --data '{ "body": "Jira Automation Message: Wrong Jira Status. Please change the Ticket to Code Merged status when opening a PR." }' -H "Content-Type: application/json" "https://beckeredu.atlassian.net/rest/api/3/issue/${JIRA_TICKET}/comment" | jq '.';
fi