#!/bin/bash

source ./functions.sh

# echo "Event type ${TRAVIS_EVENT_TYPE}"
# echo "TAG type ${TRAVIS_PULL_REQUEST}";

validate_pull_request

# if [ "$TRAVIS_PULL_REQUEST_BRANCH" = "" ]; then
#     echo "It's not a Pull Request";
# else
#     bash "${TRAVIS_BUILD_DIR}/scripts/travis/lane-verification";
# fi