<?php

use Drupal\manage_quotes\ValidateQuotes;
use Drupal\views\ViewExecutable;

/**
 * Implements hook_views_pre_render()
 */
function manage_quotes_views_pre_render(ViewExecutable $view) {
    // Accept only search_quote view
    if ($view->storage->id() != "search_quotes") {
        return;
    }

    // As the view is based on the content type Aricle
    // if the content type has more than one quote, the 
    // view will return both even if the searched term won't
    // contain in the quote
    $search_term = $view->exposed_data['body_value'];
    $validate_quotes = new ValidateQuotes($view->result, $search_term);
    $view->result = $validate_quotes->getValidQuotes();

}